name: Deploy extension

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ドキュメント通りにやっていたらこの yml は動作しない。
      #     https://shopify.dev/apps/tools/cli/ci-cd
      # ruby が必要。
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install npm dependencies
        run: yarn install

      - name: Deploy
        env:
          # Token from the Partner Dashboard
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN_EXPIRES_IN_SOME_MONTHS }}
          # .env content after a deploy
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_MY_EXTENSION_ID: ${{ secrets.SHOPIFY_MY_EXTENSION_ID }}
        run: yarn deploy
